### ISSUE TITLE
Update dependency to gnureadline

### ISSUE THREAD

**Issue by jayvdb** [pombredanne/anyreadline#3]
The `readline` package was renamed `gnureadline`.

This should use the new name.

**Comment by jayvdb** [comment]
First release on https://pypi.org/project/gnureadline/#history is 6.2.5 - Feb 16, 2014 .  That should be old enough for 99% of ppl.

Anyone wanting older versions of gnureadline would need to depend on anyreadline<=0.1.1

**Comment by yzgyyang** [comment]
Ping :) A PR is open.

**Comment by yzgyyang** [comment]
@pombredanne https://github.com/pombredanne/anyreadline/pull/5
